<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Index.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:LoginView ID="LoginView1" runat="server">
        <AnonymousTemplate>
             <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="False" AutoGenerateEditButton="False" AllowPaging="True" AllowSorting="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Model" HeaderText="Model" SortExpression="Model" />
                    <asp:BoundField DataField="Max_Speed" HeaderText="MaxSpeed" SortExpression="Max_Speed" />
                    <asp:BoundField DataField="Power" HeaderText="Power" SortExpression="Power" />
                    <asp:BoundField DataField="Color" HeaderText="Color" SortExpression="Color" />
                    <asp:BoundField DataField="fabrication_Date" HeaderText="FDate" SortExpression="fabrication_Date" />
                </Columns>
            </asp:GridView>
        </AnonymousTemplate>
        <RoleGroups>
            <asp:RoleGroup Roles="User">
                <ContentTemplate>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="False" AutoGenerateEditButton="True" AllowPaging="True" AllowSorting="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                            <asp:BoundField DataField="Model" HeaderText="Model" SortExpression="Model" />
                            <asp:BoundField DataField="Max_Speed" HeaderText="MaxSpeed" SortExpression="Max_Speed" />
                            <asp:BoundField DataField="Power" HeaderText="Power" SortExpression="Power" />
                            <asp:BoundField DataField="Color" HeaderText="Color" SortExpression="Color" />
                            <asp:BoundField DataField="fabrication_Date" HeaderText="FDate" SortExpression="fabrication_Date" />
                            <asp:HyperLinkField DataNavigateUrlFields="Id" DataNavigateUrlFormatString="~/UpdateCar.aspx?id={0}" HeaderText="Edit Car" Text="Edit" />
                        </Columns>
                    </asp:GridView>
                </ContentTemplate>
            </asp:RoleGroup>
            <asp:RoleGroup Roles="Admin">
                <ContentTemplate>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" AllowSorting="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                            <asp:BoundField DataField="Model" HeaderText="Model" SortExpression="Model" />
                            <asp:BoundField DataField="Max_Speed" HeaderText="MaxSpeed" SortExpression="Max_Speed" />
                            <asp:BoundField DataField="Power" HeaderText="Power" SortExpression="Power" />
                            <asp:BoundField DataField="Color" HeaderText="Color" SortExpression="Color" />
                            <asp:BoundField DataField="fabrication_Date" HeaderText="FDate" SortExpression="fabrication_Date" />
                            <asp:HyperLinkField DataNavigateUrlFields="Id" DataNavigateUrlFormatString="~/UpdateCar.aspx?id={0}" HeaderText="Edit Car" Text="Edit" />
                            <asp:HyperLinkField DataNavigateUrlFields="Id" DataNavigateUrlFormatString="~/DeleteCar.aspx?id={0}" HeaderText="Delete Car" Text="Delete" />
                        </Columns>
                    </asp:GridView>
                </ContentTemplate>
            </asp:RoleGroup>
        </RoleGroups>
    </asp:LoginView>
   
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" 
        SelectCommand="SELECT * FROM [Cars]"
        DeleteCommand="DELETE FROM [Cars] WHERE [Id] = @Id" 
        UpdateCommand="UPDATE [Cars] SET [Model] = @Model, [Max_Speed] = @Max_Speed, [Power] = @Power, [Color] = @Color, [fabrication_Date] = @fabrication_Date WHERE [Id] = @Id"
        ></asp:SqlDataSource>
    <asp:GridView ID="GridView2" runat="server">
    </asp:GridView>
</asp:Content>

